# Build stage
FROM node:23-alpine AS builder

RUN apk update && apk add --no-cache

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY . .

RUN npm run build

# Runtime stage
FROM node:23-alpine

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json .

RUN chown -R node:node /app

EXPOSE 80

USER node

CMD ["npm", "start"]
