name: Deploy to Homelab

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up DNS resolution
        run: |
          echo "192.168.1.5 gitea.nicolldouglas.local" | sudo tee -a /etc/hosts
          git config --global http.sslVerify false

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_IMAGE }} # Image tag

  deploy:
    name: Deploy to Production
    needs: [build-and-push]
    runs-on: ubuntu-latest

    steps:
      - name: Set up DNS resolution
        run: |
          echo "192.168.1.5 gitea.nicolldouglas.local" | sudo tee -a /etc/hosts
          git config --global http.sslVerify false

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "Setting up SSH connection"
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "Adding host public key for ${{ vars.SSH_HOST }}"
          ssh-keyscan -H ${{ vars.SSH_HOST }}

          echo "Adding credentials to SSH agent"
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          echo "SSH setup complete"

      - name: Run Deployment
        run: |
          echo "Starting deployment"
          ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "bash ${{ vars.DEPLOY_SCRIPT_PATH }}"
